service: my-lambda-service

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-1
  stage: ${opt:stage, 'lambda'}

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: newcustomer.api.vultara.com # Replace with your desired domain name
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  myFunction:
    handler: handler.myFunction
    events:
      - http:
          path: /my-endpoint
          method: GET
          cors: true  # Optionally enable CORS for the endpoint

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MyCustomAPI  # Custom name for the API Gateway resource
