service: my-api-service

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  #region: ${self:custom.region.${self:provider.stage},'us-east-1'}
  memorySize: 256
plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: newcustomer.api.vultara.com
   # domainName: ${api_name}.api.vultara.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
  myFunction:
    handler: handler.myFunction
    events:
      - http:
          path: /fakeCustomer/{proxy+}
          method: ANY
          cors: true
          #authorizer: aws_iam # or specify your authorization configuration here

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: NewCustomerApi
        #Name: ${api_name}
