service: api-server
   
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  stage: new-prod
  # stage: ${opt:stage, 'new-prod'}
plugins:
  - serverless-domain-manager
  

#####################################################################
custom:
    customDomain:
        domainName: newcustomer.api.vultara.com
        basePath: ''
        #stage: new-prod
        createRoute53Record: true
        endpointType: regional
        certificateArn: "YOUR_ACM_CERTIFICATE_ARN"
        apiType: REST
          
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: ANY
          cors: true #to enable request from diffrent domains
    ####################################################

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: NewCustomerApi
