service: api-server
custom:
  region:
   
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
 # stage: new-prod
  stage: ${opt:stage, 'new-prod'}
custom:
    customDomain:
        domainName: newcustomer.vultara.com
        basePath: ''
        stage: ${self:provider.stage}
        createRoute53Record: true
        endpointType: regional
        apiType: http
        securityPolicy: tls_1_2
        acmCertificateArn: YOUR_ACM_CERTIFICATE_ARN
       
functions:
  func:
    handler: index.handler
    url: 
      url:
      cors: true  #your function URL can be called from other domains in browsers.
    
plugins:
  #- serverless-offline
  - serverless-domain-manager
