#this file is a test only, it helped me to Automate the Lambda function with API.

service: lambda-api-server
   
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'newcustomer'}
  region: us-east-1

plugins:
  - serverless-domain-manager

custom:
    #stage: ${opt:stage, 'prod'}
    stage: ${opt:apiname, self:custom.stage}
    customDomain:
        domainName: ${self:custom.stage}.api.vultara.com
        basePath: ''
        stage: ${self:custom.stage}
        createRoute53Record: true
        createRoute53IPv6Record: false
        endpointType: regional
        certificateArn: "arn:aws:acm:us-east-1:837491041518:certificate/3fe9ff25-50e3-4be8-b99b-51b6642d1098" #Domain name*.api.vultara.com
        securityPolicy: tls_1_2
          
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: ANY
          cors: true #to enable request from diffrent domains

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name:  ${self:custom.stage}-API
