service: vultara-server

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'new-prod'}
  #region: ${self:custom.region.${self:provider.stage},'us-east-1'}
  memorySize: 256

plugins:
  - serverless-domain-manager
  - serverless-offline
custom:
    customDomain:
        domainName: newcustomer.api.vultara.com
        basePath: ''
        stage: new-prod
        createRoute53Record: true
        endpointType: regional
        certificateArn: "arn:aws:acm:us-east-1:837491041518:certificate/3fe9ff25-50e3-4be8-b99b-51b6642d1098" #Domain name*.api.vultara.com
        securityPolicy: tls_1_2
   
          
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: ANY
          cors: true #to enable request from diffrent domains

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: fakecustomer-api  #Enter Your API Gateway Name
