service: api-server
   
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  #stage: new-prod
  # stage: ${opt:stage, 'new-prod'}
plugins:
  - serverless-domain-manager
  
custom:
    STAGE: ${opt:stage, 'new-prod'}
    stagedCustomDomainProps:
        domainName:
            prod: 'newcustomer.api.vultara.com'
            staged: 'stage-newcustomer.api.vultara.com'
        basePath:
            prod: ''
            staged: ${self:custom.STAGE}
    customDomain:
        domainName: ${self:custom.stagedCustomDomainProps.domainName.${self:custom.STAGE}, self:custom.stagedCustomDomainProps.domainName.staged}
        basePath: ${self:custom.stagedCustomDomainProps.basePath.${self:custom.STAGE}, self:custom.stagedCustomDomainProps.basePath.staged}
        stage: ${self:custom.STAGE}
        createRoute53Record: true
        endpointType: regional
        apiType: REST
        #securityPolicy: tls_1_2
#####################################################################
#custom:
#    customDomain:
#        domainName: newcustomer.api.vultara.com
#        basePath: ''
##        stage: ${self:provider.stage}
 #       createRoute53Record: true
#        endpointType: regional
#        apiType: REST
          
#functions:
#  hello:
#    handler: handler.hello
#    events:
#      - http:
#          path: /
#          method: ANY
#          cors: true #to enable request from diffrent domains
    ####################################################

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: NewCustomerApi
