
# This is a basic workflow that is manually triggered

name: 0_New version and deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Type of new version (major / minor / patch)'
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major

      DeployTo:
        # Friendly description to be shown in the UI.
        description: 'Which environment do you want to deploy, default Trial and Production'
        required: true
        type: choice
        default: 'Both'
        options: 
        - Both
        - Production_Only
        - Trial_Only
        - None

      release_notes:
        description: 'Release Notes'
        # default: 'Notes'
        
# A workflow run comprises one or more jobs that can run sequentially or in parallel.

jobs:
  # This workflow contains a single job called "bump-version"
 bump-version:
  runs-on: self-hosted

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
         token: ${{ secrets.VERSION_UPDATE_WORKFLOW_TOKEN }}
         fetch-depth: 0 

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token <<< ${{ secrets.VERSION_UPDATE_WORKFLOW_TOKEN }}

    - name: Initialize mandatory git config
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email $git_email
      env:
        git_email: "${{ github.actor }}@vultara.com"

    - name: Bump version
      run: |
        npm version ${{ github.event.inputs.version }} --tag-version-prefix=""
        
    - name: Push latest version
      run: |
        git push origin main --follow-tags 
        
    - name: Extract version from branch name (for release branches)
      run: |
          new_version=$(npm version patch --tag-version-prefix="" )
          echo "RELEASE_VERSION=$new_version" >> $GITHUB_ENV
          cat "the new version is: $new_version"
    - name: Generate release notes
      run: |
        echo -e "${{ github.event.inputs.release_notes }}" > release_notes.txt
        git log $(git describe --tags --abbrev=0)..HEAD --oneline --decorate >> release_notes.txt
        
    - name: Create a new release
      run: |
        gh release create v${{ env.RELEASE_VERSION }} -t "Release v${{ env.RELEASE_VERSION }}" -F release_notes.txt
    - name: Deploy Release to both environment Trial and Production
      run: |
        echo "environment=${{ github.event.inputs.DeployTo }}" >> $GITHUB_ENV
        
    - name: Check for Conflicts
      id: check_conflicts
      run: |
          git rebase origin/prod_branch || true
          conflicts=$(git ls-files -u)
          echo "Conflicts detected: $conflicts"
          echo "::set-output name=has_conflicts::$(test -n "$conflicts" && echo true || echo false)"

    # - name: Resolve Conflicts Automatically
    #   if: steps.check_conflicts.outputs.has_conflicts == 'true'
    #   run: |

    #       conflicted_files=$(git diff --name-only --diff-filter=U)
    #       echo "Conflicted files: $conflicted_files"

    #       # Resolve conflicts
    #       for file in $conflicted_files; do
    #         git add $file
    #         git commit -m "$file is committed from conflict"
    #       done
    #       git rebase --continue
    #       git push --force-with-lease
   
    - name: Merge pre-master to prod_branch
      id: production-merge
      if: env.environment == 'Both' || env.environment == 'Production_Only'
      run: |
          gh pr create --base prod_branch --head main --title "Merge main into prod_branch" --body "Merging changes from  main into prod_branch"
          pr_number=$(gh pr list --base prod_branch --head main --json number --jq '.[0].number')
          release_notes="${{ github.event.inputs.release_notes }}"
          if [ -n "$release_notes" ]; then
            release_notes=$(echo -e "$release_notes")
            gh pr comment $pr_number --body "$release_notes"
          fi 
          echo "has_conflicts: ${{steps.check_conflicts.outputs.has_conflicts}}"
          if [ "${{ steps.check_conflicts.outputs.has_conflicts }}" == 'false' ]; then
            gh pr merge ${pr_number} --merge --admin > merge_output.txt
            echo "merge_success=true" >> $GITHUB_ENV
          else
            gh pr comment ${pr_number} --body "@M07amedRamadan the prod_branch has conflict with pre-master"
          fi
          
    - name: Merge prod_branch back to pre-master branch.
      if: env.merge_success == 'true'
      run: |
            gh pr create --base main --head prob_branch --title "Merge prod_brnach into main" --body "Merging changes from  prob_branch back to main"
            pr_url=$(gh pr list --base main --head prob_branch --json number --jq '.[0].url')
            gh pr merge $pr_url --merge --admin
          
    # - name: Send a notification about the failure.
    #   if: failure()
    #   run:  aws sns publish --topic-arn "arn:aws:sns:us-east-1:837491041518:cloudMonitoring" --message "The workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}" --subject "Release Workflow Status"
    
