#this file is a test only, it helped me to Automate the Lambda function with API.
name: Deploying lambda with API Name
on:

  #push:
   # branches:
    # - test_New_ARC
  workflow_dispatch:
   # inputs:
   #   domainName:
    #    description: 'Enter the domain name'
     #   required: true
     #   default: "Mohamed"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust to the node version you need
        

      - name: Install serverless
        run: npm install -g serverless

      - name: Deploy with Serverless
        run: |
          cd api
          serverless plugin install -n serverless-domain-manager
          export API_NAME=customerName
          sls create_domain --stage newcustomer
          sls deploy --stage newcustomer   # Modify the stage as needed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
