name: Deploy Serverless Service

on:
 workflow_dispatch:
  inputs:
   name:
     description: "Enter the API name"
     default: "newcustomer"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to the node version you need

      - name: Install dependencies
        run: npm install -g serverless

      - name: Deploy to AWS
        run: |
          cd ./api
          serverless deploy --stage ${{ github.event_name }} --api_name ${{ github.event.inputs.name }}  # You can set your API name dynamically here
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
