
on:
  workflow_dispatch:

name: Auto Release Process_Do not Touch

jobs:
#   # publish:
#   #   name: Publish to npm
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - uses: actions/checkout@v4
#   #     - uses: actions/setup-node@v4
#   #       with:
#   #         node-version: '14'
#   #         cache: 'npm'
#   #     - name: Publish
#   #       run: |
#   #         npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
#   #         npm ci
#   #         npm publish
#   #       env:
#   #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

#   create-github-release:
#     name: Create GitHub Release
#     if: startsWith(github.ref, 'refs/tags/')
#     runs-on: ubuntu-latest
#     permissions:
#       deployments: write
#       contents: write
#       statuses: write
#     # needs: publish

#     steps:
#       - name: Extract version from branch name (for release branches)
#         run: |
#           BRANCH_NAME="${{ github.ref }}"
#           VERSION=${BRANCH_NAME#refs/tags/}
#           echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
#       - name: Create Release Notes
#         uses: actions/github-script@v7
#         with:
#           github-token: ${{github.token}}
#           script: |
#             await github.request(`POST /repos/${{ github.repository }}/releases`, {
#               tag_name: "${{ github.ref }}",
#               name: "v${{ env.RELEASE_VERSION }} release",
#               generate_release_notes: true
#             });
