on:
  push:
    tags:
      - '*'

name: Auto Release Process_Do not Touch

jobs:
  # publish:
  #   name: Publish to npm
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '14'
  #         cache: 'npm'
  #     - name: Publish
  #       run: |
  #         npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  #         npm ci
  #         npm publish
  #       env:
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: write
      statuses: write
    # needs: publish
    outputs: 
      RELEASE_ID: ${{ steps.release.outputs.releaseI}}

    steps:
      - name: Extract version from branch name (for release branches)
        run: |
          BRANCH_NAME="${{ github.ref }}"
          VERSION=${BRANCH_NAME#refs/tags/}
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create Release Notes
        id: release
        uses: actions/github-script@v7
        with:
          github-token: ${{github.token}}
          script: |
              const response = await github.request('POST /repos/${{ github.repository }}/releases', {
              tag_name: "${{ github.ref }}",
              name: "v${{ env.RELEASE_VERSION }} release",
              generate_release_notes: true
                });
              # const releaseId = response.data.id;
              # echo "releaseId= $releaseId" >> GITHUB_OUTPUT
    

  append-notes:
    needs: create-github-release
    runs-on: ubuntu-latest
    env: 
      RELEASE_ID: ${{ needs.create-github-release.outputs.RELEASE_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print the release ID
        run: echo "the releaseID is= ${{env.RELEASE_ID}} "
      - name: Append Notes to Release
        uses: actions/github-script@v5
        with:
          script: |
             const releaseId = '${{env.RELEASE_ID}}';
              await github.request('POST /repos/${{ github.repository }}/releases/${releaseId}/update', {
                body: "Additional release notes here"
              });
