name: Destroy CloudFormation Stack

on:
  # push:
  #   branches:
  #    - main
  workflow_dispatch:
   inputs:
      Stack_Name:
        description: 'AWS CloudFormation stack name'

jobs:
  # destroy-stack:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-2 # Replace with your AWS region

  #     - name: Delete CloudFormation Stack
  #       run: |
  #         if [ -n "${{ github.event.inputs.Stack_Name }}" ]; then
  #             echo "Start deletion Stack"
  #             aws cloudformation delete-stack --stack-name ${{ github.event.inputs.Stack_Name }}
  #             aws cloudformation wait stack-delete-complete --stack-name ${{ github.event.inputs.Stack_Name }} 
  #         else
  #             echo "The user not using SOC App" 
  #         fi
        # aws cloudformation get-template --stack-name ${{ github.event.inputs.Stack_Name }} --query TemplateBody --output text > current-template.yaml
        # chmod +w current-template.yaml
        # ls -la
        # sed -i'' -e 's/Retain/Delete/g' current-template.yaml            
        # cat current-template.yaml
        # aws cloudformation validate-template --template-body file://current-template.yaml
        #echo "after update"             aws cloudformation update-stack --stack-name ${{ github.event.inputs.Stack_Name }} --template-body file://current-template.yaml --capabilities CAPABILITY_IAM

        #aws cloudformation get-template --stack-name ${{ github.event.inputs.Stack_Name }}
  second-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Delete CloudFormation Stack
        run: |
            aws cloudformation get-template --stack-name ${{ github.event.inputs.Stack_Name }} --query TemplateBody --output text > template.json
            jq '.Resources | to_entries[] | select(.value.DeletionPolicy == "Retain") | .key' template.json

            
        # resources=$(aws cloudformation describe-stack-resources --stack-name ${{ github.event.inputs.Stack_Name }} --query 'StackResources[*].LogicalResourceId' --output text)
        # retained_resources=$(aws cloudformation describe-stack-resources --stack-name ${{ github.event.inputs.Stack_Name }} --query "StackResources[?ResourceType==\`$resources\`].LogicalResourceId" --output text)
        # echo "$retained_resources"


