name: Destroy CloudFormation Stack

on:
  workflow_dispatch:

jobs:
  destroy-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack --stack-name automate-destroy-test
          aws cloudformation wait stack-delete-complete --stack-name automate-destroy-test
