name: Destroy CloudFormation Stack

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  destroy-stack:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Delete CloudFormation Stack
        run: |
            aws cloudformation get-template --stack-name automate-destroy-test --query TemplateBody --output text > current-template.yaml
            chmod +w current-template.yaml
            ls -la
            sed -i'' -e 's/Retain/Delete/g' current-template.yaml            
            cat current-template.yaml
            echo "validating... "
            aws cloudformation validate-template --template-body file://current-template.yaml
            echo "validation done... "
            aws cloudformation update-stack --stack-name automate-destroy-test --template-body current-template.yaml --capabilities CAPABILITY_IAM automate-destroy-test

            


        # cat ./template.yml
        # sed -i 's/"Retain"/"Delete"/g' ./template.yml
        # cat ./template.yml            aws cloudformation update-stack --stack-name automate-destroy-test --template-body current-template.yaml

        #  aws cloudformation get-template --stack-name automate-destroy-test  --output template.json

            
        #cat template.json

        
          #aws cloudformation delete-stack --stack-name automate-deletion-test
          #aws cloudformation wait stack-delete-complete --stack-name automate-deletion-test
