name: "Destroy primary IAC Deployment"

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
  pull_request:
    branches:
      - TestNewCustomerVpc
  



jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
      
    steps:

      - name: Checkout
        uses: actions/checkout@v2
