name: "New Customer IaC Deployment"

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Enter Customer Name'
        default: 'automation'
        required: true

      vpc-cidr:
        description: 'Enter the VPC CIDR'
        default: '10.1.7.0/24'
        required: true

      region:
        description: 'Enter the Region for Deployment'
        default: 'us-east-1'
        required: true
      
      public_subnet-1:
        description: 'Enter the CIDRs for Public Subnet 1'
        default: '10.1.7.0/26'
        required: true

      public_subnet-2:
        description: 'Enter the CIDRs for Public Subnet 2'
        default: '10.1.7.64/26'
        required: true

      private_subnet-1:
        description: 'Enter the CIDRs for Private Subnet 1'
        default: '10.1.7.128/26'
        required: true

      private_subnet-2:
        description: 'Enter the CIDRs for Private Subnet 2'
        default: '10.1.7.192/26'
        required: true

      instance-type:
        description: 'Enter the Intance Type for EC2 Instance Scheduler'
        default: 't2.small'
        required: true
        type: choice
        options:
          - 't2.small'
          - 't2.medium'
          - 't2.large'
          - 't3.small'
          - 't3.medium'
          - 't3.large'

      ami-type:
        description: 'Enter the AMI Type for EC2 Instance Scheduler'
        default: 'ami-007855ac798b5175e'
        required: true
        type: choice
        options:
          - 'ami-007855ac798b5175e' #Ubuntu 22.04
          - 'ami-06878d265978313ca' #Amazon Linux 2 

      key-name:
        description: 'Enter the KeyPair Name for EC2 Instance Scheduler'
        default: 'automation_test'
        required: true


jobs:
  prodConsulting-deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: read
      statuses: write
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
