name: self runner

on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  prod-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Production
      run: |
        echo "Production"
        sleep 1000

   
