name: Run Python script

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install boto3
        run: pip install boto3
      - name: VPC CIDRs already in-use
        run: python vpc_cidr.py

